from .token_type import TokenType


class Token:
    """A simple token class. These are generated by Lexer and consumed by Parser."""

    type: TokenType
    text: str
    start: int
    end: int
    line: int

    def __init__(self, type: TokenType, text: str, position: int, line: int):
        self.type = type
        self.text = text
        self.end = position + 1
        self.start = self.end - len(self.text)
        if self.start < 1:
            self.start = 1
        self.line = line

    def __str__(self) -> str:
        return self.text

    def __repr__(self) -> str:
        return "{}({}, {}):{}:{}".format(
            type(self).__name__, repr(self.type), f"'{self.text}'", str(self.line), str(self.start)
        )
