using Harpy.Lexer;
using Harpy.Parser;

namespace HarpyTests.ParserTests;

[TestClass]
public sealed class TestExpressionParser
{
    [TestMethod]
    public void TestCall()
    {
        AssertParsedEqualsExpected(
            "a()",
            """
            CallExpression(
                function
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a(b)",
            """
            CallExpression(
                function
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[2:4))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a(b, c)",
            """
            CallExpression(
                function
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[2:4))
                    )
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[5:7))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a(, b)",
            """
            CallExpression(
                function
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                arguments
                │
                └───nil
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[4:6))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a(b)(c)",
            """
            CallExpression(
                function
                │
                └───CallExpression(
                        function
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        arguments
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[5:7))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a(b) + c(d)",
            """
            OperatorExpression(
                left
                │
                └───CallExpression(
                        function
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        arguments
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                operator
                │
                └───Token('+',1,[5:7))
                right
                │
                └───CallExpression(
                        function
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[7:9))
                            )
                        arguments
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('d',1,[9:11))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a(@b) + c(@d)",
            """
            OperatorExpression(
                left
                │
                └───CallExpression(
                        function
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        arguments
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('@',1,[2:4))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[3:5))
                                    )
                            )
                    )
                operator
                │
                └───Token('+',1,[6:8))
                right
                │
                └───CallExpression(
                        function
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[8:10))
                            )
                        arguments
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('@',1,[10:12))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('d',1,[11:13))
                                    )
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestUnaryPrecedence()
    {
        AssertParsedEqualsExpected(
            "++a",
            """
            PrefixExpression(
                operator
                │
                └───Token('++',1,[1:3))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[2:4))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "++--a",
            """
            PrefixExpression(
                operator
                │
                └───Token('++',1,[1:3))
                right
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('--',1,[2:5))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[4:6))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "++a--",
            """
            PrefixExpression(
                operator
                │
                └───Token('++',1,[1:3))
                right
                │
                └───PostfixExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[2:4))
                            )
                        operator
                        │
                        └───Token('--',1,[3:6))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!-+a",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:2))
                right
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('-',1,[1:3))
                        right
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('+',1,[2:4))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[3:5))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!-++a",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:2))
                right
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('-',1,[1:3))
                        right
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('++',1,[2:5))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[4:6))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!-a++",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:2))
                right
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('-',1,[1:3))
                        right
                        │
                        └───PostfixExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[2:4))
                                    )
                                operator
                                │
                                └───Token('++',1,[3:6))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!!!a",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:2))
                right
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('!',1,[1:3))
                        right
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('!',1,[2:4))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[3:5))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "@a",
            """
            PrefixExpression(
                operator
                │
                └───Token('@',1,[1:2))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:3))
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestUnaryOrBinaryPrecedence()
    {
        AssertParsedEqualsExpected(
            "-a * b",
            """
            OperatorExpression(
                left
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('-',1,[1:2))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:3))
                            )
                    )
                operator
                │
                └───Token('*',1,[3:5))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[5:7))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "-a % b",
            """
            OperatorExpression(
                left
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('-',1,[1:2))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:3))
                            )
                    )
                operator
                │
                └───Token('%',1,[3:5))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[5:7))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!a + b",
            """
            OperatorExpression(
                left
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('!',1,[1:2))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:3))
                            )
                    )
                operator
                │
                └───Token('+',1,[3:5))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[5:7))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!a ^ b",
            """
            OperatorExpression(
                left
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('!',1,[1:2))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:3))
                            )
                    )
                operator
                │
                └───Token('^',1,[3:5))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[5:7))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "-a",
            """
            PrefixExpression(
                operator
                │
                └───Token('-',1,[1:2))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:3))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!a",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:2))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:3))
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestBinaryPrecedence()
    {
        AssertParsedEqualsExpected(
            "a := b + c * d ^ e - f / g",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───OperatorExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[5:7))
                                    )
                                operator
                                │
                                └───Token('+',1,[7:9))
                                right
                                │
                                └───OperatorExpression(
                                        left
                                        │
                                        └───NameExpression(
                                                name
                                                │
                                                └───Token('c',1,[9:11))
                                            )
                                        operator
                                        │
                                        └───Token('*',1,[11:13))
                                        right
                                        │
                                        └───OperatorExpression(
                                                left
                                                │
                                                └───NameExpression(
                                                        name
                                                        │
                                                        └───Token('d',1,[13:15))
                                                    )
                                                operator
                                                │
                                                └───Token('^',1,[15:17))
                                                right
                                                │
                                                └───NameExpression(
                                                        name
                                                        │
                                                        └───Token('e',1,[17:19))
                                                    )
                                            )
                                    )
                            )
                        operator
                        │
                        └───Token('-',1,[19:21))
                        right
                        │
                        └───OperatorExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('f',1,[21:23))
                                    )
                                operator
                                │
                                └───Token('/',1,[23:25))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('g',1,[25:27))
                                    )
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestBinaryAssociativity()
    {
        AssertParsedEqualsExpected(
            "a := b := c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───AssignmentExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := b = c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('=',1,[7:9))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[9:11))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := b == c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('==',1,[7:10))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := b < c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('<',1,[7:9))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[9:11))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := b <= c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('<=',1,[7:10))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := b # c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('#',1,[5:7))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[7:9))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := b != c",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('!=',1,[7:10))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a + b - c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('+',1,[2:4))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                    )
                operator
                │
                └───Token('-',1,[6:8))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[8:10))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a + b > c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('+',1,[2:4))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                    )
                operator
                │
                └───Token('>',1,[6:8))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[8:10))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a + b >= c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('+',1,[2:4))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                    )
                operator
                │
                └───Token('>=',1,[6:9))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[9:11))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a * b / c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('*',1,[2:4))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                    )
                operator
                │
                └───Token('/',1,[6:8))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[8:10))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a ^ b ^ c",
            """
            OperatorExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                operator
                │
                └───Token('^',1,[2:4))
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                        operator
                        │
                        └───Token('^',1,[6:8))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[8:10))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a^b^c",
            """
            OperatorExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                operator
                │
                └───Token('^',1,[1:3))
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                        operator
                        │
                        └───Token('^',1,[3:5))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[4:6))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a * b % c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('*',1,[2:4))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                    )
                operator
                │
                └───Token('%',1,[6:8))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[8:10))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a $ b $ c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('$',1,[2:4))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[4:6))
                            )
                    )
                operator
                │
                └───Token('$',1,[6:8))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[8:10))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a .or. b",
            """
            OperatorExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                operator
                │
                └───Token('.or.',1,[2:7))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[7:9))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a .and. b",
            """
            OperatorExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                operator
                │
                └───Token('.and.',1,[2:8))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[8:10))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a .and. b .or. c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('.and.',1,[2:8))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[8:10))
                            )
                    )
                operator
                │
                └───Token('.or.',1,[10:15))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[15:17))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a .or. b .and. c",
            """
            OperatorExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                operator
                │
                └───Token('.or.',1,[2:7))
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[7:9))
                            )
                        operator
                        │
                        └───Token('.and.',1,[9:15))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[15:17))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!a .and. !b .or. !c",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('!',1,[1:2))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[1:3))
                                    )
                            )
                        operator
                        │
                        └───Token('.and.',1,[3:9))
                        right
                        │
                        └───PrefixExpression(
                                operator
                                │
                                └───Token('!',1,[9:11))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[10:12))
                                    )
                            )
                    )
                operator
                │
                └───Token('.or.',1,[12:17))
                right
                │
                └───PrefixExpression(
                        operator
                        │
                        └───Token('!',1,[17:19))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[18:20))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "!(a .or. b .and. c)",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:2))
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[2:4))
                            )
                        operator
                        │
                        └───Token('.or.',1,[4:9))
                        right
                        │
                        └───OperatorExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[9:11))
                                    )
                                operator
                                │
                                └───Token('.and.',1,[11:17))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('c',1,[17:19))
                                    )
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestGrouping()
    {
        AssertParsedEqualsExpected(
            "a + (b + c) + d",
            """
            OperatorExpression(
                left
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        operator
                        │
                        └───Token('+',1,[2:4))
                        right
                        │
                        └───OperatorExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[5:7))
                                    )
                                operator
                                │
                                └───Token('+',1,[7:9))
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('c',1,[9:11))
                                    )
                            )
                    )
                operator
                │
                └───Token('+',1,[12:14))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('d',1,[14:16))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a ^ (b + c)",
            """
            OperatorExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                operator
                │
                └───Token('^',1,[2:4))
                right
                │
                └───OperatorExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[5:7))
                            )
                        operator
                        │
                        └───Token('+',1,[7:9))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[9:11))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "(!a)",
            """
            PrefixExpression(
                operator
                │
                └───Token('!',1,[1:3))
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[2:4))
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestLiterals()
    {
        AssertParsedEqualsExpected(
            ".t.",
            """
            LiteralExpression(
                literal(type=boolean)
                │
                └───Token('.t.',1,[1:4))
            )
            """
        );
        AssertParsedEqualsExpected(
            "123",
            """
            LiteralExpression(
                literal(type=number)
                │
                └───Token('123',1,[1:4))
            )
            """
        );
        AssertParsedEqualsExpected(
            "'hello'",
            """
            LiteralExpression(
                literal(type=string)
                │
                └───Token("'hello'",1,[1:8))
            )
            """
        );
        AssertParsedEqualsExpected(
            "NIL",
            """
            LiteralExpression(
                literal(type=nil)
                │
                └───Token('NIL',1,[1:4))
            )
            """
        );
        AssertParsedEqualsExpected(
            "nil",
            """
            LiteralExpression(
                literal(type=nil)
                │
                └───Token('nil',1,[1:4))
            )
            """
        );
    }

    [TestMethod]
    public void TestObjectAccess()
    {
        AssertParsedEqualsExpected(
            "a:b",
            """
            ObjectAccessExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('b',1,[2:4))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b:c",
            """
            ObjectAccessExpression(
                left
                │
                └───ObjectAccessExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[4:6))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b()",
            """
            CallExpression(
                function
                │
                └───ObjectAccessExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b(c)",
            """
            CallExpression(
                function
                │
                └───ObjectAccessExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[4:6))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b():c",
            """
            ObjectAccessExpression(
                left
                │
                └───CallExpression(
                        function
                        │
                        └───ObjectAccessExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[1:2))
                                    )
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[2:4))
                                    )
                            )
                    )
                right
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[6:8))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b()[1]",
            """
            IndexExpression(
                left
                │
                └───CallExpression(
                        function
                        │
                        └───ObjectAccessExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[1:2))
                                    )
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[2:4))
                                    )
                            )
                    )
                index
                │
                └───LiteralExpression(
                        literal(type=number)
                        │
                        └───Token('1',1,[6:8))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b()['key']",
            """
            IndexExpression(
                left
                │
                └───CallExpression(
                        function
                        │
                        └───ObjectAccessExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[1:2))
                                    )
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[2:4))
                                    )
                            )
                    )
                index
                │
                └───LiteralExpression(
                        literal(type=string)
                        │
                        └───Token("'key'",1,[6:12))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b()[1 + c]",
            """
            IndexExpression(
                left
                │
                └───CallExpression(
                        function
                        │
                        └───ObjectAccessExpression(
                                left
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('a',1,[1:2))
                                    )
                                right
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[2:4))
                                    )
                            )
                    )
                index
                │
                └───OperatorExpression(
                        left
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[6:8))
                            )
                        operator
                        │
                        └───Token('+',1,[8:10))
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestArrayDeclarator()
    {
        AssertParsedEqualsExpected(
            "a := { }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ArrayDeclaratorExpression()
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { 1 }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ArrayDeclaratorExpression(
                        element 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[7:9))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { 1, 2 }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ArrayDeclaratorExpression(
                        element 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[7:9))
                            )
                        element 1
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('2',1,[10:12))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { 1, b() }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ArrayDeclaratorExpression(
                        element 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[7:9))
                            )
                        element 1
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[10:12))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { ;\n    1, ;\n    b() ;\n}",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ArrayDeclaratorExpression(
                        element 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',2,[4:6))
                            )
                        element 1
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',3,[4:6))
                                    )
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestHashDeclarator()
    {
        AssertParsedEqualsExpected(
            "a := { => }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───HashDeclaratorExpression()
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { 'b' => 1 }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───HashDeclaratorExpression(
                        key 0
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'b'",1,[7:11))
                            )
                        value 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[14:16))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { 'b' => 1, 'c' => 2 }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───HashDeclaratorExpression(
                        key 0
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'b'",1,[7:11))
                            )
                        value 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[14:16))
                            )
                        key 1
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'c'",1,[17:21))
                            )
                        value 1
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('2',1,[24:26))
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { 'b' => 1, 'c' => d() }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───HashDeclaratorExpression(
                        key 0
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'b'",1,[7:11))
                            )
                        value 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[14:16))
                            )
                        key 1
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'c'",1,[17:21))
                            )
                        value 1
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('d',1,[24:26))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { ;\n    'b' => 1, ;\n    'c' => d() ;\n}",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───HashDeclaratorExpression(
                        key 0
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'b'",2,[4:8))
                            )
                        value 0
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',2,[11:13))
                            )
                        key 1
                        │
                        └───LiteralExpression(
                                literal(type=string)
                                │
                                └───Token("'c'",3,[4:8))
                            )
                        value 1
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('d',3,[11:13))
                                    )
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestCodeblock()
    {
        AssertParsedEqualsExpected(
            "a := { || b() }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───CodeblockExpression(
                        expressions
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[10:12))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { |b| c(b) }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───CodeblockExpression(
                        parameters
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[8:10))
                            )
                        expressions
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('c',1,[11:13))
                                    )
                                arguments
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[13:15))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { |b,c| d(b, c) }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───CodeblockExpression(
                        parameters
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[8:10))
                            )
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                        expressions
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('d',1,[13:15))
                                    )
                                arguments
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[15:17))
                                    )
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('c',1,[18:20))
                                    )
                            )
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a := { |b,c| d(b), e(c) }",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───CodeblockExpression(
                        parameters
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[8:10))
                            )
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('c',1,[10:12))
                            )
                        expressions
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('d',1,[13:15))
                                    )
                                arguments
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('b',1,[15:17))
                                    )
                            )
                        │
                        └───CallExpression(
                                function
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('e',1,[19:21))
                                    )
                                arguments
                                │
                                └───NameExpression(
                                        name
                                        │
                                        └───Token('c',1,[21:23))
                                    )
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestConditional()
    {
        AssertParsedEqualsExpected(
            "a := iif(b, 1, 0)",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ConditionalExpression(
                        if
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[9:11))
                            )
                        then
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[12:14))
                            )
                        else
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('0',1,[15:17))
                            )
                    )
            )
            """
        );

        AssertParsedEqualsExpected(
            "a := iif(b, 1, )",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ConditionalExpression(
                        if
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[9:11))
                            )
                        then
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('1',1,[12:14))
                            )
                        else
                        │
                        └───nil
                    )
            )
            """
        );

        AssertParsedEqualsExpected(
            "a := iif(b, , 0)",
            """
            AssignmentExpression(
                left
                │
                └───NameExpression(
                        name
                        │
                        └───Token('a',1,[1:2))
                    )
                right
                │
                └───ConditionalExpression(
                        if
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[9:11))
                            )
                        then
                        │
                        └───nil
                        else
                        │
                        └───LiteralExpression(
                                literal(type=number)
                                │
                                └───Token('0',1,[14:16))
                            )
                    )
            )
            """
        );
    }

    [TestMethod]
    public void TestComments()
    {
        AssertParsedEqualsExpected(
            "a:b(c/* Not sure if this should be here */)",
            """
            CallExpression(
                function
                │
                └───ObjectAccessExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[4:6))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b(/* Not sure if this should be here */c)",
            """
            CallExpression(
                function
                │
                └───ObjectAccessExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[41:43))
                    )
            )
            """
        );
        AssertParsedEqualsExpected(
            "a:b(c) // Comment at the end",
            """
            CallExpression(
                function
                │
                └───ObjectAccessExpression(
                        left
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('a',1,[1:2))
                            )
                        right
                        │
                        └───NameExpression(
                                name
                                │
                                └───Token('b',1,[2:4))
                            )
                    )
                arguments
                │
                └───NameExpression(
                        name
                        │
                        └───Token('c',1,[4:6))
                    )
            )
            """
        );
    }

    private static void AssertParsedEqualsExpected(string source, string expected)
    {
        var lexer = new Lexer(source);
        var reader = new SourceReader(lexer);
        var parser = new ExpressionParser(reader);

        var result = parser.Parse();
        var actual = result?.PrettyPrint();
        Assert.AreEqual(expected.Replace("\r\n", "\n"), actual);
    }
}
