from .token_type import TokenType


class Token:
    """A simple token class. These are generated by Lexer and consumed by Parser."""

    _type: TokenType
    _text: str

    def __init__(self, type: TokenType, text: str):
        self._type = type
        self._text = text

    def __str__(self) -> str:
        return self._text

    def __repr__(self) -> str:
        return "{}({}, {})".format(
            type(self).__name__, repr(self._type), f"'{self._text}'"
        )

    def get_type(self) -> TokenType:
        return self._type

    def get_text(self) -> str:
        return self._text
